name : "Developer CI"
On:
  push:
    branches: 
     - developer

    jobs:
      test:
        runs-on: ubuntu-latest
        name : Checkout Code
        uses: actions/checkout@v4

        name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
        name : Build and Test    
        run: mvn test