name: Simple CI

on:
  push:
    branches:
      - developer

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: BookStore-Rest-API

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Project
        run: mvn clean install
